name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.9
      uses: actions/setup-python@v2 
      with:
        python-version: 3.9.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install urllib3
        pip install django
        pip install djangorestframework
        pip install codecs
        
        
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`

